on:
  push:
  schedule:
  - cron: '*/5 * * * *'
defaults:
  run:
    shell: bash
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Get latest version
      run: |-
        curl --silent --show-error https://hex-rays.com/updida | python -c "import re, sys; print(re.sub(r'<[^>]+?>', '', re.search(r'Latest available version: <strong>IDA and decompilers (.*?)</strong>', sys.stdin.read()).group(1)))" >version.txt
    - name: Notify and commit if dirty
      if: github.ref == 'refs/heads/master'
      env:
        NOTIFY_TOKEN: ${{ secrets.NOTIFY_TOKEN }}
      run: |-
        if [ -n "$(git status --porcelain)" ]; then
        	curl --header 'Content-Type: text/plain; charset=utf-8' --header "X-Access-Token: $NOTIFY_TOKEN" --data-binary @version.txt "https://youfu.work/hooks/github-ida-update"
        	git config --global user.name 'GitHub Actions'
        	git config --global user.email "$(whoami)@$(hostname --fqdn)"
        	git add --all
        	git commit --all --message 'IDA updated'
        	git push
        fi
